### ISSUE TITLE
Just Some General Questions About Tork Wheel

### ISSUE THREAD

**Issue by BlueDev5** [adrenak/Tork#12]
I Just Have A sigle Question That I Wanna Know How You Managed To Keep Tires On The Ground without Colliders?

**Comment by adrenak** [comment]
Hi @Amogh-Mittal that happens in TorkWheel.cs as tork doesn't use WheelCollider. [Here](https://github.com/adrenak/tork/blob/17ae6323c00732e1dcb2b8ebb4ec166f24146833/Assets/Tork/Runtime/Core/TorkWheel.cs#L187) you can see that the wheel raycast is used to calculate two things:

- The force that the suspension spring must apply. This is Hooke's law of springs.
- Second is, the force applied is damped based on the rate of change of compression from line 197 onwards. This basically simulates energy loss and is so that the car comes to a balanced state else the car will keep on bouncing (try setting springDamper to 0 to see that happen).

When the wheel raycast is hitting the ground, the force is applied, when the ray doesn't hit anything it doesn't. 

The final force is hookes force - damping. The starting of [this video](https://youtu.be/3NHVSIlCOTs) may give some idea.

**Comment by BlueDev5** [comment]
Oh ok now I understand it thanks for telling.🙂
